nelmio_api_doc:
    documentation:
        servers:
            - url: https://localhost:8000
              description: API SimRacing
        info:
            title: SimRacing API
            description: API Documentation pour SimRacing
            version: 1.0.0
        components:
            schemas:
                LoginRequest:
                    type: object
                    required:
                        - username
                        - password
                    properties:
                        username:
                            type: string
                            example: admin@simracing.com
                        password:
                            type: string
                            example: admin
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            example: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9..."
                User:
                    type: object
                    properties:
                        id:
                            type: integer
                        email:
                            type: string
                        firstName:
                            type: string
                        lastName:
                            type: string
                        createdAt:
                            type: string
                            format: date-time
                UserCreate:
                    type: object
                    required:
                        - email
                        - password
                        - firstName
                        - lastName
                    properties:
                        email:
                            type: string
                            format: email
                            example: user@example.com
                        password:
                            type: string
                            example: password123
                        firstName:
                            type: string
                            example: John
                        lastName:
                            type: string
                            example: Doe
                Contact:
                    type: object
                    required:
                        - name
                        - email
                        - subject
                        - message
                    properties:
                        name:
                            type: string
                            example: John Doe
                        email:
                            type: string
                            format: email
                            example: john@example.com
                        subject:
                            type: string
                            example: Demande d'information
                        message:
                            type: string
                            example: Je souhaiterais avoir plus d'informations...
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
                    description: 'Entrer le token JWT (sans le préfixe Bearer)'
        security:
            - Bearer: []
        paths:
            /api/login_check:
                post:
                    tags:
                        - Authentication
                    summary: Connexion pour obtenir un token JWT
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/LoginRequest'
                    responses:
                        '200':
                            description: Connexion réussie
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$|/doc.json$)
