controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check
    methods: ['POST']

# Documentation API
api_doc:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui
    methods: GET

api_doc_json:
    path: /api/doc.json
    controller: nelmio_api_doc.controller.swagger
    methods: GET

# Routes Contact
contact_api:
    path: /api/contact
    controller: App\Controller\ContactController::contact
    methods: POST

contact_page:
    path: /contact
    controller: App\Controller\ContactController::index
    methods: GET
